# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cdd63e0976b057c632133bde978b931e1e3b98a178de24f9d04fe528ec25c703b5c195b121c452fa92e855c14a250d622c8b66ede798c0b013399d5a3847876

test:
  secret_key_base: cb32e292cb4fe375752d9b29658b7dd8b3a6a21e5d38fe550d404eabe647014346d249531a0f8c35fbfa6f411fe0d50d179af56bb459bcdf577cf47cc89dc80c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
